#=========================================================================
# OpenRAM SRAM Compiler 
#=========================================================================
# Author : Kartik Prabhu
# Date   : February 15, 2020
#

name: sram

#-------------------------------------------------------------------------
# Outputs
#-------------------------------------------------------------------------

outputs:
  - sram.sp
  - sram.v
  - sram.lef
  - sram_tt_1p8V_25C.lib
  - sram_tt_1p8V_25C.db
  - sram.gds
  - design.vcs.v
  - sram_input_db.lib
  - sram_weight_db.lib
  - sram_accum_buff.lib
  - ccs_ram_sync_1R1W.h
  - ccs_ram_sync_1R1W_trans_rsc.h
  - testbench.sv
  - design.args

#-------------------------------------------------------------------------
# Commands
#-------------------------------------------------------------------------

commands:
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_4kbyte_1rw1r_32x1024_8/sky130_sram_4kbyte_1rw1r_32x1024_8.sp              outputs/sram.sp
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_4kbyte_1rw1r_32x1024_8/sky130_sram_4kbyte_1rw1r_32x1024_8.v               outputs/sram.v
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_4kbyte_1rw1r_32x1024_8/sky130_sram_4kbyte_1rw1r_32x1024_8.lef             outputs/sram.lef
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_4kbyte_1rw1r_32x1024_8/sky130_sram_4kbyte_1rw1r_32x1024_8_TT_1p8V_25C.lib outputs/sram_tt_1p8V_25C.lib
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_4kbyte_1rw1r_32x1024_8/sky130_sram_4kbyte_1rw1r_32x1024_8.gds             outputs/sram.gds
  - cp /farmshare/home/classes/ee/272/sky130_sram_macros/sky130_sram_4kbyte_1rw1r_32x1024_8/sky130_sram_4kbyte_1rw1r_32x1024_8_TT_1p8V_25C.db  outputs/sram_tt_1p8V_25C.db
  - catapult -shell -file scripts/sram_input_db.tcl
  - catapult -shell -file scripts/sram_weight_db.tcl
  - catapult -shell -file scripts/sram_accum_buff.tcl
  - cp src/sram_wrapper.v                outputs/design.vcs.v
  - cp sram_input_db.lib                 outputs/sram_input_db.lib
  - cp sram_weight_db.lib                outputs/sram_weight_db.lib
  - cp sram_accum_buff.lib               outputs/sram_accum_buff.lib
  - cp ccs_ram_sync_1R1W.h               outputs/ccs_ram_sync_1R1W.h
  - cp ccs_ram_sync_1R1W_trans_rsc.h     outputs/ccs_ram_sync_1R1W_trans_rsc.h
  - cp src/sram_tb.sv                    outputs/testbench.sv

